<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260217154203 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ranking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, usuario_id INT NOT NULL, cartas_id VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_80B839D0DB38439E ON ranking (usuario_id)');
        $this->addSql('CREATE INDEX IDX_80B839D0303ACA92 ON ranking (cartas_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE ranking ADD CONSTRAINT FK_80B839D0DB38439E FOREIGN KEY (usuario_id) REFERENCES onetcg.usuario (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ranking ADD CONSTRAINT FK_80B839D0303ACA92 FOREIGN KEY (cartas_id) REFERENCES onetcg.carta (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE onetcg.carta DROP notas');
        $this->addSql('ALTER TABLE onetcg.carta ALTER id TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE onetcg.carta ALTER tipo SET NOT NULL');
        $this->addSql('ALTER TABLE onetcg.expansiones ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE onetcg.expansiones ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX onetcg.expansiones_nombre_expansion_key RENAME TO UNIQ_E302E2B71CB9168');
        $this->addSql('ALTER TABLE onetcg.imagenes ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE onetcg.imagenes ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE onetcg.imagenes ALTER id_carta TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE onetcg.imagenes ALTER id_carta SET NOT NULL');
        $this->addSql('ALTER TABLE onetcg.imagenes ALTER tamanyo SET NOT NULL');
        $this->addSql('ALTER TABLE onetcg.resenya ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE onetcg.resenya ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE onetcg.resenya ALTER id_usuario SET NOT NULL');
        $this->addSql('ALTER TABLE onetcg.resenya ALTER id_carta TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE onetcg.resenya ALTER id_carta SET NOT NULL');
        $this->addSql('ALTER INDEX onetcg.resenya_id_usuario_id_carta_key RENAME TO resenya_usuario_carta_unique');
        $this->addSql('ALTER TABLE onetcg.usuario ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE onetcg.usuario ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX onetcg.usuario_username_key RENAME TO UNIQ_50CAE2C6F85E0677');
        $this->addSql('ALTER INDEX onetcg.usuario_email_key RENAME TO UNIQ_50CAE2C6E7927C74');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ranking DROP CONSTRAINT FK_80B839D0DB38439E');
        $this->addSql('ALTER TABLE ranking DROP CONSTRAINT FK_80B839D0303ACA92');
        $this->addSql('DROP TABLE ranking');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE onetcg.carta ADD notas TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE onetcg.carta ALTER id TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE onetcg.carta ALTER tipo DROP NOT NULL');
        $this->addSql('ALTER TABLE onetcg.expansiones ALTER id SET DEFAULT nextval(\'onetcg.expansiones_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE onetcg.expansiones ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX onetcg.uniq_e302e2b71cb9168 RENAME TO expansiones_nombre_expansion_key');
        $this->addSql('ALTER TABLE onetcg.imagenes ALTER id SET DEFAULT nextval(\'onetcg.imagenes_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE onetcg.imagenes ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE onetcg.imagenes ALTER tamanyo DROP NOT NULL');
        $this->addSql('ALTER TABLE onetcg.imagenes ALTER id_carta TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE onetcg.imagenes ALTER id_carta DROP NOT NULL');
        $this->addSql('ALTER TABLE onetcg.resenya ALTER id SET DEFAULT nextval(\'onetcg.resenya_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE onetcg.resenya ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE onetcg.resenya ALTER id_usuario DROP NOT NULL');
        $this->addSql('ALTER TABLE onetcg.resenya ALTER id_carta TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE onetcg.resenya ALTER id_carta DROP NOT NULL');
        $this->addSql('ALTER INDEX onetcg.resenya_usuario_carta_unique RENAME TO resenya_id_usuario_id_carta_key');
        $this->addSql('ALTER TABLE onetcg.usuario ALTER id SET DEFAULT nextval(\'onetcg.usuario_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE onetcg.usuario ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX onetcg.uniq_50cae2c6f85e0677 RENAME TO usuario_username_key');
        $this->addSql('ALTER INDEX onetcg.uniq_50cae2c6e7927c74 RENAME TO usuario_email_key');
    }
}
