<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260207094955 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA onetcg');
        $this->addSql('CREATE TABLE onetcg.carta (id VARCHAR(50) NOT NULL, rarity VARCHAR(20) DEFAULT NULL, tipo VARCHAR(50) NOT NULL, nombre VARCHAR(255) NOT NULL, coste INT DEFAULT NULL, atributo_nombre VARCHAR(50) DEFAULT NULL, atributo_icono_url TEXT DEFAULT NULL, poder INT DEFAULT NULL, counter INT DEFAULT NULL, color VARCHAR(50) DEFAULT NULL, familia TEXT DEFAULT NULL, habilidad TEXT DEFAULT NULL, efecto_trigger TEXT DEFAULT NULL, id_expansion INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EF78A849705CE755 ON onetcg.carta (id_expansion)');
        $this->addSql('CREATE TABLE onetcg.expansiones (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre_expansion VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E302E2B71CB9168 ON onetcg.expansiones (nombre_expansion)');
        $this->addSql('CREATE TABLE onetcg.imagenes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tamanyo VARCHAR(10) NOT NULL, url TEXT NOT NULL, id_carta VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_50C5859F533C7AD4 ON onetcg.imagenes (id_carta)');
        $this->addSql('CREATE TABLE onetcg.resenya (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, puntuacion NUMERIC(3, 1) NOT NULL, comentario TEXT DEFAULT NULL, id_usuario INT NOT NULL, id_carta VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F8863A7BFCF8192D ON onetcg.resenya (id_usuario)');
        $this->addSql('CREATE INDEX IDX_F8863A7B533C7AD4 ON onetcg.resenya (id_carta)');
        $this->addSql('CREATE UNIQUE INDEX resenya_usuario_carta_unique ON onetcg.resenya (id_usuario, id_carta)');
        $this->addSql('CREATE TABLE onetcg.usuario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(50) NOT NULL, email VARCHAR(255) NOT NULL, contrasenya VARCHAR(255) NOT NULL, roles JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_50CAE2C6F85E0677 ON onetcg.usuario (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_50CAE2C6E7927C74 ON onetcg.usuario (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE onetcg.carta ADD CONSTRAINT FK_EF78A849705CE755 FOREIGN KEY (id_expansion) REFERENCES onetcg.expansiones (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE onetcg.imagenes ADD CONSTRAINT FK_50C5859F533C7AD4 FOREIGN KEY (id_carta) REFERENCES onetcg.carta (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE onetcg.resenya ADD CONSTRAINT FK_F8863A7BFCF8192D FOREIGN KEY (id_usuario) REFERENCES onetcg.usuario (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE onetcg.resenya ADD CONSTRAINT FK_F8863A7B533C7AD4 FOREIGN KEY (id_carta) REFERENCES onetcg.carta (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE onetcg.carta DROP CONSTRAINT FK_EF78A849705CE755');
        $this->addSql('ALTER TABLE onetcg.imagenes DROP CONSTRAINT FK_50C5859F533C7AD4');
        $this->addSql('ALTER TABLE onetcg.resenya DROP CONSTRAINT FK_F8863A7BFCF8192D');
        $this->addSql('ALTER TABLE onetcg.resenya DROP CONSTRAINT FK_F8863A7B533C7AD4');
        $this->addSql('DROP TABLE onetcg.carta');
        $this->addSql('DROP TABLE onetcg.expansiones');
        $this->addSql('DROP TABLE onetcg.imagenes');
        $this->addSql('DROP TABLE onetcg.resenya');
        $this->addSql('DROP TABLE onetcg.usuario');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
