<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

// SECCIÓN: Migración — Resincronizar secuencias de identidad
final class Version20260222120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Resincroniza las secuencias IDENTITY de todas las tablas para evitar conflictos de clave primaria';
    }

    public function up(Schema $schema): void
    {
        // Las secuencias se corrigen en postUp con SQL dinámico
    }

    public function postUp(Schema $schema): void
    {
        // SECCIÓN: Resincronizar secuencias IDENTITY de todas las tablas del esquema onetcg
        // Las columnas usan GENERATED BY DEFAULT AS IDENTITY, cuya secuencia interna
        // se resetea con ALTER COLUMN id RESTART WITH, no con setval.
        $tablas = ['expansiones', 'imagenes', 'resenya', 'usuario', 'ranking'];

        foreach ($tablas as $tabla) {
            $maxId = (int) $this->connection->fetchOne("SELECT COALESCE(MAX(id), 0) FROM onetcg.$tabla");
            $this->connection->executeStatement(
                "ALTER TABLE onetcg.$tabla ALTER COLUMN id RESTART WITH " . ($maxId + 1)
            );
        }
    }

    public function down(Schema $schema): void
    {
        // No hay reversión posible para este tipo de corrección
    }
}
